"""Add cooker_id to deliveries

Revision ID: a500148669a1
Revises: 
Create Date: 2025-10-09 16:23:28.105643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a500148669a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooker_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['cooker_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cooker_id')

    # ### end Alembic commands ###
